/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBack: typeof import('./src/components/AppBack.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppI18nSwitch: typeof import('./src/components/AppI18nSwitch.vue')['default']
    AppLocaleSwitch: typeof import('./src/components/AppLocaleSwitch.vue')['default']
    AppMobileDetector: typeof import('./src/components/AppMobileDetector.vue')['default']
    AppSideMenu: typeof import('./src/components/AppSideMenu.vue')['default']
    AppThemeSwitch: typeof import('./src/components/AppThemeSwitch.vue')['default']
    AppUADetector: typeof import('./src/components/AppUADetector.vue')['default']
    copy: typeof import('./src/components/MobileDetector copy.vue')['default']
    MobileDetector: typeof import('./src/components/MobileDetector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterStack: typeof import('./src/components/RouterStack.vue')['default']
    RouterStackView: typeof import('./src/components/RouterStackView.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCel: typeof import('@varlet/ui')['_CelComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarEllipsis: typeof import('@varlet/ui')['_EllipsisComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarIndexAnchor: typeof import('@varlet/ui')['_IndexAnchorComponent']
    VarIndexBar: typeof import('@varlet/ui')['_IndexBarComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarPullRefresh: typeof import('@varlet/ui')['_PullRefreshComponent']
    VarResult: typeof import('@varlet/ui')['_ResultComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
